//
//  FoodAddViewController.m
//  EatTrainSleepRepeat
//
//  Created Artem Balashov on 26/02/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "FoodAddViewController.h"
#import <UIKit/UIKit.h>

@interface FoodAddViewController () <FoodAddView>

@end

@implementation FoodAddViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    [self configureUI];
    [self.presenter viewDidLoad];
}

// MARK: - UI Configuration

- (void)configureUI {
    self.view.backgroundColor = [UIColor whiteColor];
    //configure UI
    self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemStop target:self action:@selector(didSelectDismissButton)];
}

- (void)didSelectDismissButton {
    [self.presenter didSelectDismissButton];
}

- (void)displayTitle:(nonnull NSString *)title {
    self.navigationItem.title = title;
}

@end
