//
//  FoodAddConfigurator.h
//  EatTrainSleepRepeat
//
//  Created Artem Balashov on 26/02/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <UIKit/UIKit.h>

@interface FoodAddConfigurator: NSObject

+ (UIViewController *)createModuleWithTitle:(NSString*)title;

@end
