//
//  FoodAddPresenter.h
//  EatTrainSleepRepeat
//
//  Created Artem Balashov on 26/02/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "FoodAddProtocols.h"

@interface FoodAddPresenter: NSObject<FoodAddPresenterInterface>
@property (nonatomic, weak) NSObject<FoodAddView> *view;
- (instancetype)initWithView:(NSObject<FoodAddView>*)view
                      router:(NSObject<FoodAddWireframeInterface>*)router
                       title:(NSString*)title;
@end


