//
//  FoodAddRouter.m
//  EatTrainSleepRepeat
//
//  Created Artem Balashov on 26/02/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "FoodAddRouter.h"
#import "FoodAddProtocols.h"

@implementation FoodAddRouter


- (void)navigateToDismiss { 
    [self.viewController dismissViewControllerAnimated:true completion:nil];
}

@end
