//
//  FoodAddProtocols.h
//  EatTrainSleepRepeat
//
//  Created Artem Balashov on 26/02/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@protocol FoodAddWireframeInterface <NSObject>

- (void)navigateToDismiss;
@end

@protocol FoodAddView <NSObject>

- (void)displayTitle:(NSString *)title;

@end

@protocol FoodAddPresenterInterface <NSObject>

- (void)didSelectDismissButton;

- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)viewWillDissappear;
- (void)viewDidDissappear;

@end


NS_ASSUME_NONNULL_END
