//
//  FoodAddConfigurator.m
//  EatTrainSleepRepeat
//
//  Created Artem Balashov on 26/02/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "FoodAddConfigurator.h"
#import "FoodAddViewController.h"
#import "FoodAddPresenter.h"
#import "FoodAddProtocols.h"
#import "FoodAddRouter.h"

@interface FoodAddConfigurator ()

@end

@implementation FoodAddConfigurator

+ (UIViewController *)createModuleWithTitle:(NSString*)title {
    FoodAddViewController *view = [[FoodAddViewController alloc] init];
    FoodAddRouter *router = [[FoodAddRouter alloc] init];
    FoodAddPresenter *presenter = [[FoodAddPresenter alloc] initWithView:view router:router title:title];
    view.presenter = presenter;
    UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:view];
    router.viewController = view;
    return nav;
}

@end
