//
//  FoodAddPresenter.m
//  EatTrainSleepRepeat
//
//  Created Artem Balashov on 26/02/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "FoodAddPresenter.h"
#import "FoodAddProtocols.h"

@interface FoodAddPresenter () <FoodAddPresenterInterface>
@property (strong, nonatomic) NSObject<FoodAddWireframeInterface>* router;
@property (strong, nonatomic) NSString *title;
@end

@implementation FoodAddPresenter

- (instancetype)initWithView:(NSObject<FoodAddView>*)view
                      router:(NSObject<FoodAddWireframeInterface>*)router
                       title:(NSString *)title
{
    self = [super init];
    if (self) {
        self.view = view;
        self.router = router;
        self.title = title;
    }
    return self;
}

- (void)viewDidAppear {
    //Default implementation
}

- (void)viewDidDissappear {
    //Default implementation
}

- (void)viewDidLoad {
    [self.view displayTitle:self.title];
}

- (void)viewWillAppear {
    //Default implementation
}

- (void)viewWillDissappear {
    //Default implementation
}

- (void)didSelectDismissButton {
    [self.router navigateToDismiss];
}


@end
